// <auto-generated />
namespace projeto01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_produto_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_produto_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040521452_add_produto_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
