// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ItemCarrinho_to_coontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemCarrinho_to_coontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201912271617148_ItemCarrinho_to_coontext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
