// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class picdowload_fild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(picdowload_fild));
        
        string IMigrationMetadata.Id
        {
            get { return "201912251854566_picdowload_fild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
